# This file was generated by https://github.com/lionello/dub2nix v0.4.1
[ {
  fetch = {
    type = "git";
    url = "https://github.com/vibe-d/vibe-inet.git";
    rev = "v1.0.0";
    sha256 = "1f1wiarsxzll79phfnwnqfj11mac0jcpnqy65p0106j4bpd7p844";
    fetchSubmodules = false;
    date = "2024-02-17T12:59:22+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/myrgi4rv56j65lmfzy84adg4a6nkj6qy-vibe-inet";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/vibe-d/vibe-stream.git";
    rev = "v1.1.0";
    sha256 = "0nqm25m88mr04sf858wcan12sdlasks11h4im2awc8kjhqpz8iaf";
    fetchSubmodules = false;
    date = "2024-02-20T09:13:26+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/bkk24fidlnjnl1kg4rx39m0fllhllrrh-vibe-stream";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/vibe-d/vibe-core.git";
    rev = "v2.8.6";
    sha256 = "1wz21cqzx5kji1rlhl4w30b3nfnl4bq5hc01xsxi2pf04jyq8p3f";
    fetchSubmodules = false;
    date = "2024-07-23T11:14:59+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/6ai0r7kkyn02zaql6y0z8cmgv29s7zmg-vibe-core";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/etcimon/memutils.git";
    rev = "v1.0.10";
    sha256 = "0vscncyf6i0skd4c0srzfc4xxx987336f89zdjhq6750jd00njqg";
    fetchSubmodules = false;
    date = "2023-12-18T19:11:53-05:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/fmiak6lhmy7lgj5m9zxzlkxa5favc560-memutils";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/s-ludwig/taggedalgebraic.git";
    rev = "v0.11.23";
    sha256 = "1qkkii2xygskj2h9k681wx323m398ym8zr8a8gpcf3rfkl9ki49c";
    fetchSubmodules = false;
    date = "2024-04-18T13:16:41+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/yawh6zmad9c9fxm7x1k6zl9i56c1cz0k-taggedalgebraic";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/vibe-d/vibe-container.git";
    rev = "v1.3.1";
    sha256 = "1zhd39h48v6bf9y3390r743av2fbpd7ddk78ahrbmgla4vjjn994";
    fetchSubmodules = false;
    date = "2024-04-02T08:55:27+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/c7n88ql1y5y6d5iw80wpcd4bvfd327ck-vibe-container";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/vibe-d/vibe.d.git";
    rev = "v0.10.0";
    sha256 = "1z6yqbfjryk0ck2548l45kiwc4kal4i3kf4hycnz9anlqk4kxs7l";
    fetchSubmodules = false;
    date = "2024-02-17T19:34:41+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/9k0a14dr85czxv9ykfqbfwjigi2nbga8-vibe.d";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/vibe-d/vibe-http.git";
    rev = "v1.1.1";
    sha256 = "0nls9y8h74xrn8vv6r1gq2n5lgmri1xwyxmrlxfxrfkwqzqknb74";
    fetchSubmodules = false;
    date = "2024-07-12T16:07:23+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/jpmk7q1rapj217xg5sir3ya2s59sw8q1-vibe-http";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/wilzbach/stdx-allocator.git";
    rev = "v2.77.5";
    sha256 = "03av8zp5p6vf6fg005xbmwnjfw96jyrr4dcj4m56c4a3vx7v72pk";
    fetchSubmodules = false;
    date = "2018-12-23T13:54:22+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/b3h25asfh205wzwjfzjf2k2kkccpp96k-stdx-allocator";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/vibe-d/vibe-serialization.git";
    rev = "v1.0.4";
    sha256 = "0fiha9ivhhzd41g4srpq6xz3p5vl9j2yiwcp2zyc672f644zx0ya";
    fetchSubmodules = false;
    date = "2024-06-10T18:18:19+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/0m53q4c6321fplq3d8yak460idhfz1b4-vibe-serialization";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/rejectedsoftware/diet-ng.git";
    rev = "v1.8.1";
    sha256 = "11hrbvsxhipvcz9m1qlq92iaw0h35pzdy5rf7z8c4vx3hwjrnhni";
    fetchSubmodules = false;
    date = "2022-04-22T11:38:43+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/xziliy9ah3s3ah8mslnxsw47n4w6wkca-diet-ng";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/D-Programming-Deimos/openssl.git";
    rev = "v3.3.3";
    sha256 = "1634j4psp3qwgwhk2sa3jj6gvwv3i96hpg2wrdy9ihjhabnszn0f";
    fetchSubmodules = false;
    date = "2023-09-14T12:05:32+00:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/i3pgh154r80xvh4vsnl6srg6khmk5dg7-openssl";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/vibe-d/eventcore.git";
    rev = "v0.9.31";
    sha256 = "004fsakgqyqdq1fcmg7cpb30q13y2iqswklmqvraw3j6fwm7502g";
    fetchSubmodules = false;
    date = "2024-07-08T13:16:14+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/r5gzs525kwgnbkx6r5i2damnr5jm9r0p-eventcore";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/libmir/mir-linux-kernel.git";
    rev = "v1.0.1";
    sha256 = "1gcaavsni47352nvw9s41zkaswd582cafq3931i0zinhd9s3clag";
    fetchSubmodules = false;
    date = "2018-08-04T16:03:31+07:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/qz6axwci8kb1477j9dzgq85nscjfyvj1-mir-linux-kernel";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/etcimon/libasync.git";
    rev = "v0.8.6";
    sha256 = "1pbvlfxbp3p0ld0552dzdl4ng5939f84drjbcj8a7g199p1ih045";
    fetchSubmodules = false;
    date = "2020-02-22T09:07:54-05:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/6l82qf5nav5pkbvnrhcs5v9vwj5xycq3-libasync";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/bildhuus/deimos-openssl-static.git";
    rev = "v1.0.5+3.0.8";
    sha256 = "18a8cvsip7ncdmadczxms6z2vfldifv8mqsgwh9rcyz56b8fby0r";
    fetchSubmodules = false;
    date = "2024-04-19T18:58:55+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/zvp8r2xlnmlwcrk1yfb169n56sb1pgr3-deimos-openssl-static";
  };
} ]