title: Eskolan Koodipaja
author: Ate Eskola
email: ajieskola@gmail.com
postaddress1: Saratie 5 b 3
postaddress2: 85500 Nivala
description: >-
  Eskolan Koodipajan kotisivut.
baseurl: ""
url: "https://koodipaja.ate-eskola.fi"
github_username: dukc
linkedin_username: ate-eskola-a80202323
theme: minima
header_pages:
  - "palvelut.md"
  - "mies.md"
  - "näytöt.md"
  - "sivu.md"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
